# Generated by Django 5.0.7 on 2024-07-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captcha',
            options={'verbose_name': '验证码表', 'verbose_name_plural': '验证码表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '历史记录表', 'verbose_name_plural': '历史记录表'},
        ),
    ]
