# Generated by Django 5.0.7 on 2024-07-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_usergroup'),
        ('users', '0002_alter_captcha_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='usergroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.usergroup', verbose_name='用户组'),
            preserve_default=False,
        ),
    ]
