# Generated by Django 5.0.7 on 2024-07-22 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_type_choice_option'),
        ('users', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('correct', models.BooleanField(verbose_name='是否正确')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='问题')),
            ],
            options={
                'verbose_name': '历史记录表',
                'verbose_name_plural': '历史记录表',
                'db_table': 'history',
                'ordering': ['-create_time'],
            },
        ),
    ]
