# Generated by Django 5.0.7 on 2024-07-25 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_usergroup_type'),
        ('users', '0003_comment_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.usergroup', verbose_name='用户组'),
        ),
    ]
