# Generated by Django 5.0.7 on 2024-07-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='historys',
            field=models.ManyToManyField(related_name='history', to='users.history', verbose_name='历史记录'),
        ),
    ]
