# Generated by Django 5.0.7 on 2024-07-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_historys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
