# Generated by Django 4.2.14 on 2024-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="问题标题")),
                ("content", models.TextField(verbose_name="问题内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("fill_in_the_blank", "Fill in the Blank"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="问题类型",
                    ),
                ),
                (
                    "ans",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="答案"
                    ),
                ),
                ("is_all", models.BooleanField(default=True, verbose_name="是否为全部题目")),
            ],
            options={
                "verbose_name": "问题表",
                "verbose_name_plural": "问题表",
                "db_table": "questions",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="QuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="问题组标题")),
                (
                    "content",
                    models.TextField(default="作者很懒，什么都没有留下", verbose_name="问题组内容"),
                ),
            ],
            options={
                "verbose_name": "问题组表",
                "verbose_name_plural": "问题组表",
                "db_table": "question_groups",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="标签名称"),
                ),
            ],
            options={
                "verbose_name": "标签表",
                "verbose_name_plural": "标签表",
                "db_table": "tags",
                "ordering": ["-create_time"],
            },
        ),
    ]
