# Generated by Django 4.2.14 on 2024-07-22 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiongroup",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AddField(
            model_name="questiongroup",
            name="members",
            field=models.ManyToManyField(
                related_name="member_question_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="组员",
            ),
        ),
        migrations.AddField(
            model_name="questiongroup",
            name="questions",
            field=models.ManyToManyField(
                related_name="question_groups",
                to="questions.question",
                verbose_name="问题",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="choices",
            field=models.ManyToManyField(
                related_name="questionsChoices",
                to="questions.choice",
                verbose_name="选项",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                related_name="questionsTags", to="questions.tag", verbose_name="标签"
            ),
        ),
    ]
