# Generated by Django 5.0.7 on 2024-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.TextField(default=None, verbose_name='问题答案'),
        ),
    ]
