# Generated by Django 5.0.7 on 2024-07-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '选项表', 'verbose_name_plural': '选项表'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '问题表', 'verbose_name_plural': '问题表'},
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'verbose_name': '问题组表', 'verbose_name_plural': '问题组表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签表', 'verbose_name_plural': '标签表'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option',
        ),
    ]
