# Generated by Django 5.0.7 on 2024-07-25 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_choice_options_alter_question_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='用户组标题')),
                ('content', models.TextField(default='作者很懒，什么都没有留下', verbose_name='用户组内容')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('members', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='组员')),
            ],
            options={
                'verbose_name': '用户组表',
                'verbose_name_plural': '用户组表',
                'db_table': 'user_groups',
            },
        ),
    ]
