# Generated by Django 5.0.7 on 2024-07-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Type', models.CharField(default='multiple_choice', max_length=5, verbose_name='选项类型')),
                ('content', models.TextField(verbose_name='选项内容')),
            ],
            options={
                'verbose_name': '选项表',
                'verbose_name_plural': '选项表',
                'db_table': 'choices',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_in_the_blank', 'Fill in the Blank'), ('single_choice', 'Single Choice')], default='single_choice', max_length=20, verbose_name='问题类型'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='questionsChoices', to='questions.choice', verbose_name='选项'),
        ),
    ]
