# Generated by Django 5.0.7 on 2024-07-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_choice_alter_question_type_question_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Type',
            new_name='option',
        ),
    ]
