# Generated by Django 5.0.7 on 2024-07-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='type',
            field=models.CharField(choices=[('academic', '学术版'), ('enterprise', '企业版'), ('person', '个人版'), ('other', '其他')], default='person', max_length=20, verbose_name='群组类型'),
        ),
    ]
