# Generated by Django 5.0.7 on 2024-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_usergroup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='is_all',
            field=models.BooleanField(default=False, verbose_name='是否所有人可见'),
        ),
    ]
