# Generated by Django 5.0.7 on 2024-07-25 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_questiongroup_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_question_groups', to=settings.AUTH_USER_MODEL, verbose_name='组员'),
        ),
    ]
